### ISSUE TITLE
Feature: automatic homework machine

### ISSUE THREAD

**Issue by doowzs** [Maxwell-Lyu/SE2019#1]
I need an automatic homework machine. You learn computer science so you are able to make one!

Features I want:

- Automatically writes homework,
- Always get 100 marks.

**Comment by Maxwell-Lyu** [comment]
你在想🍑

**Comment by Tyler-ytr** [comment]
Amazing!

**Comment by Michael1015198808** [comment]
Since many homework does not have plain file format, I hope your machine can handle picture or audio.

**Comment by Tyler-ytr** [comment]
可能であれば、複数のシステムプラットフォームをサポートすることを希望します

**Comment by doowzs** [comment]
助けで、ドラえもん

**Comment by doowzs** [comment]
Great news! We have an automatic homework machine now! 1920271
